// DSL -> Java源码生成
package com.example.demo.service;

import com.example.demo.model.TestCase;
import org.springframework.stereotype.Service;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.List;

/**
 * TestCodeGeneratorService
 * ------------------------------------
 * 功能：
 * 1. 接收 DSL 生成的 TestCase 列表
 * 2. 将这些 TestCase 转换成 Java 源代码
 * 3. 每次生成一个 Java 文件：AutoGeneratedTests.java
 * 输入：List<TestCase>
 * 输出：Java测试类文件（.java）
 * 小白理解：
 * 这个类就是“把自动化平台的 JSON 测试用例 → 变成真正能运行的 Java JUnit 测试代码”
 */
@Service
public class TestCodeGeneratorService {

    // Java 源文件输出的位置
    private final String outputDir = "src/test/java/com/example/autotest/generated/";

    /**
     * 生成 Java 测试类
     *
     * @param cases 用例列表
     * @param className 类名
     */
    public File generateJavaTestClass(List<TestCase> cases, String className) throws IOException {

        StringBuilder sb = new StringBuilder();

        // 包名 & 导入类
        sb.append("package com.example.autotest.generated;\n\n");
        sb.append("import org.junit.jupiter.api.Test;\n");
        sb.append("import static org.junit.jupiter.api.Assertions.*;\n");
        sb.append("import java.net.http.*;\n");
        sb.append("import java.net.URI;\n");
        sb.append("import java.time.Duration;\n\n");
        sb.append("public class ").append(className).append(" {\n\n");

        // 为每个 TestCase 生成一个 @Test 方法
        for (TestCase tc : cases) {
            sb.append("    @Test\n");
            sb.append("    public void ").append(tc.getCaseId()).append("() throws Exception {\n");
            sb.append("        System.out.println(\"Running case: ").append(tc.getCaseId()).append("\");\n");

            // HTTP 客户端
            sb.append("        HttpClient client = HttpClient.newHttpClient();\n");

            // 生成不同类型的请求（这里简化 GET/POST）
            if (tc.getApi().getMethod().equalsIgnoreCase("GET")) {
                sb.append("        HttpRequest request = HttpRequest.newBuilder()\n")
                        .append("            .uri(new URI(\"")
                        .append(tc.getApi().getBaseUrl()).append(tc.getApi().getPath())
                        .append("\"))\n")
                        .append("            .timeout(Duration.ofSeconds(5))\n")
                        .append("            .GET()\n")
                        .append("            .build();\n");
            } else {
                sb.append("        HttpRequest request = HttpRequest.newBuilder()\n")
                        .append("            .uri(new URI(\"")
                        .append(tc.getApi().getBaseUrl()).append(tc.getApi().getPath())
                        .append("\"))\n")
                        .append("            .timeout(Duration.ofSeconds(5))\n")
                        .append("            .POST(HttpRequest.BodyPublishers.ofString(\"{}\"))\n")
                        .append("            .build();\n");
            }

            // 执行 HTTP 请求
            sb.append("        HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString());\n");

            // 生成断言（状态码）
            sb.append("        assertEquals(")
                    .append(tc.getExpected().getStatus()).append(", response.statusCode());\n");

            // Body contains 断言
            if (tc.getExpected().getExpectedBodyContains() != null) {
                sb.append("        assertTrue(response.body().contains(\"")
                        .append(tc.getExpected().getExpectedBodyContains())
                        .append("\"));\n");
            }

            sb.append("    }\n\n");
        }

        sb.append("}\n");

        // 文件输出
        File dir = new File(outputDir);
        if (!dir.exists()) dir.mkdirs();

        File javaFile = new File(dir, className + ".java");
        try (FileWriter writer = new FileWriter(javaFile)) {
            writer.write(sb.toString());
        }

        return javaFile;
    }
}
