package com.example.demo.controller;

import com.example.demo.model.ApiEndpoint;
import com.example.demo.model.GenerateCodeRequest;
import com.example.demo.service.ParserService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
import java.util.Map;

@Controller
public class ApiController {

    @Autowired
    private ParserService parserService;
    // 前端展示接口
    @GetMapping("/")
    public String index() { return "index"; }

    // 解析接口
    @PostMapping("/api/parse")
    @ResponseBody
    public List<ApiEndpoint> parse(@RequestParam("file") MultipartFile file) throws Exception {
        return parserService.parseSwaggerFile(file);
    }

    // 测试代码生成接口，接收前端提交的任务和场景，返回自动生成的测试代码，这个版本是手动生成的，后期可以换成AI自动生成
    @PostMapping("/api/generate")
    @ResponseBody
    public String generateCode(@RequestBody GenerateCodeRequest request) {
        StringBuilder fullCode = new StringBuilder();

        fullCode.append("// 自动生成的测试代码\n");
        fullCode.append("package com.example.demo.test;\n\n");
        fullCode.append("import org.junit.jupiter.api.Test;\n");
        fullCode.append("import java.util.HashMap;\n");
        fullCode.append("import java.util.Map;\n\n");
        fullCode.append("public class AutoGeneratedTests {\n\n");
        // 遍历每个任务和场景生成测试方法
        int testCounter = 1;

        for (GenerateCodeRequest.ApiTask task : request.getTasks()) {
            for (GenerateCodeRequest.TestScenario scenario : task.getScenarios()) {

                // 生成测试方法名
                String methodName = "test_" + task.getMethod() + "_" + testCounter++;
                fullCode.append(String.format("    @Test\n    public void %s() {\n", methodName));
                fullCode.append(String.format("        // 场景: %s\n", scenario.getScenarioName()));
                fullCode.append(String.format("        // 接口: %s %s\n", task.getMethod(), task.getApiPath()));

                fullCode.append("        // 1. 准备参数\n");

                Map<String, GenerateCodeRequest.ParamValueInfo> params = scenario.getParamValues();
                if (params != null) {
                    params.forEach((key, info) -> {
                        String finalValue;

                        // 1. 如果用户在网页填了值，就直接用
                        if (info.getValue() != null && !info.getValue().isEmpty()) {
                            // 如果是字符串，加上双引号
                            finalValue = "\"" + info.getValue() + "\"";
                        }
                        // 2. 如果没填，根据类型生成 TODO 占位符
                        else {
                            finalValue = generateSmartPlaceholder(info.getType(), key);
                        }

                        // 生成变量定义代码
                        String javaType = mapToJavaType(info.getType());
                        fullCode.append(String.format("        %s %s = %s;\n", javaType, key, finalValue));
                    });
                }

                fullCode.append("\n        // 2. 发起请求 (模拟)\n");
                fullCode.append("        System.out.println(\"Sending request to \" + \"" + task.getApiPath() + "\");\n");
                fullCode.append("        // TODO: 调用 Feishu SDK 或 HttpClient\n");
                fullCode.append("        // client.send(...);\n\n");

                fullCode.append("        // 3. 断言结果\n");
                fullCode.append("        // Assert.assertEquals(" + scenario.getExpectedStatusCode() + ", response.code());\n");
                fullCode.append("    }\n\n");
            }
        }

        fullCode.append("}\n");
        return fullCode.toString();
    }

    // 辅助方法：根据 Swagger 类型生成 Java 默认值/占位符
    private String generateSmartPlaceholder(String swaggerType, String paramName) {
        if (swaggerType == null) return "null";

        switch (swaggerType.toLowerCase()) {
            case "string":
                // 针对特定字段名做个优化
                if (paramName.contains("id")) return "\"TODO_FILL_ID\"";
                return "\"TODO_FILL_STRING\"";
            case "integer":
            case "number":
                return "0"; // 默认数字
            case "boolean":
                return "false";
            case "object":
            case "json":
                // 模拟一个空的 JSON 字符串
                return "\"{\\\"key\\\": \\\"value\\\"}\"";
            default:
                return "null";
        }
    }

    // 辅助方法：Swagger 类型转 Java 类型
    private String mapToJavaType(String swaggerType) {
        if (swaggerType == null) return "Object";
        switch (swaggerType.toLowerCase()) {
            case "string": return "String";
            case "integer": return "Integer";
            case "number": return "Double";
            case "boolean": return "Boolean";
            default: return "Object";
        }
    }
}