package com.example.demo.controller;

import com.example.demo.model.CoverageReport;
import com.example.demo.model.TestCase;
import com.example.demo.model.TestRunResult;
import com.example.demo.service.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.io.File;
import java.util.List;

/**
 * AutoTestController
 * -------------------------------------
 * 小白理解：
 * 前端（页面）调用这个接口：
 * 1. 传入测试用例 JSON
 * 2. 系统自动生成 Java 源码
 * 3. 自动编译
 * 4. 自动执行
 * 5. 自动生成报告
 * 一键完成所有自动化流程！
 */
@RestController
@RequestMapping("/test")
public class AutoTestController {

    @Autowired
    private TestCodeGeneratorService generator;

    @Autowired
    private DynamicCompilerService compiler;

    @Autowired
    private TestExecutorService executor;

    @Autowired
    private ApiSceneAnalyzerService analyzer;

    @Autowired
    private ReportGeneratorService reporter;

    /**
     * 一键生成 → 编译 → 执行 → 出报告
     */
    @PostMapping("/run")
    public CoverageReport runAutoTests(@RequestBody List<TestCase> cases) throws Exception {

        // 1. 生成 Java 文件
        File javaFile = generator.generateJavaTestClass(cases, "AutoGeneratedTests");

        // 2. 动态编译
        boolean ok = compiler.compile(javaFile);
        if (!ok) throw new RuntimeException("编译失败");

        // 3. 执行测试
        List<TestRunResult> results =
                executor.execute("com.example.autotest.generated.AutoGeneratedTests");

        // 4.计算理论接口场景数
        // todo:需先将输入文档解析为ApiDoc格式
        List<String> scenes = analyzer.analyze(apiDoc);


        // 4. 生成覆盖率报告
        return reporter.calculate(scenes, cases);
    }
}
